name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # altere para a sua branch principal se for diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy src to root
        run: cp -r src/* .

      - name: Deploy
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy"
          git push origin main  # altere para a sua branch principal se for diferente
